### PR TITLE
Changed % complete listing from >=25% and =100% to >=25%, >=50%, >=75%, and =100%

### PR DESCRIPTION
**Pull request by Gaffi**
Changed % complete listing from _>=25%_ and _=100%_ to _>=25%_, _>=50%_, _>=75%_, and _=100%_

### CODE REVIEW

**Comment by kelnage** [comment]
Thanks for the suggestion.

Unfortunately, on my browser this causes the Steam Gifts table to grow so large that the [header is larger than the background gradient](http://i.imgur.com/KNAwWh9.png) (you'll see a dark bar at the bottom of the header in that image). This is why I've been limiting the number of rows that I have added to the table.

I'm considering doing an alternative visualisation to show the distribution of the completion percentages, but haven't got around to it yet. I'm happy for you to keep running your fork or if you can display those stats nicely within that constraint., I'll happily accept your pull request.

**Comment by Gaffi** [comment]
Sure, I'll see if I can find a way to make that work (but I'm a little doubtful). I'll update if I come up with something.

**Comment by Gaffi** [comment]
Actually, I think I found a solution already. Posted the update for your review.

**Comment by kelnage** [comment]
Ah, nice find. I'm still a little reluctant to make the table "too big" (for some value of "too big", I guess). You'll see I've made a new commit that includes a "sparkline" of a user's achievement percentages, which enables you to more easily view this information, with a bit more detail. If you want to update it to the latest version (1.4.0) and see what I've done, I'd be interested to hear your thoughts and whether it does what you're looking for. If not we could have a look at merging your PR.

**Comment by Gaffi** [comment]
I didn't get notified of your comment, sorry. I'll take a look at your new version. :)

**Comment by Gaffi** [comment]
I like the idea, but I have a few pieces of feedback. The label "Games with Achievements" is just a tad too long for my resolution (I think that's the issue). When I see the chart, the text link is right beside the label. When I see the text, the chart link wraps to the next line. I changed this to "Achievement Rates" and it worked fine.

It's pretty difficult to see the small changes with what's displayed as the scale makes it hard to distinguish. I modified the height to 20px (auto = 14px), and that seemed to work better for me, but expanded the canvas as my original fork did, so I left it as-is. I think, after working with it enough, I got used to the format and  I'm ok with the size now.

I didn't change enough to warrant a merge from my code, IMO, but I posted it anyway.

Overall, the chart is a nice solution, plus the tooltip gets the job of actually identifying all the values. I Like it!

**Pull request merged**
